### ISSUE TITLE
Fatal error when using gem

### ISSUE THREAD

**Issue by Cissi-B** [tanaylab/umi4cpackage#12]
Hi,

I am trying to create a new database for umi4cPackage by following the umi4c-newDB vignette. However, when I try to build the mappability bedgraph using gem, I get the following error message when running the gem-indexer:

`Creating sequence and location files...Fatal error: exception Failure("Command 'echo "-------gem-indexer_fasta2meta+cont" > equCab3_index.log && gem-indexer_fasta2meta+cont -i equCab3.fa.gz -c dna --filter-function iupac-dna --strip-unknown-bases-threshold 50 --complement-size-threshold 2000000000 --complement emula
`
I have been trying to solve this but have not yet succeeded. Do you know what the problem could be and how I can solve it?

Thank you in advance! :)

**Comment by lldelisle** [comment]
Hi,
Did you install gem2 with conda?
Did you run `gem-indexer -T ${nbThreads} -c dna -i ${fastaFile} -o ${genome}_index`?
If yes, can you check all variables are set:
```
echo $nbThreads
echo $fastaFile
echo $genome
```
Can you give the the full log ?
Thanks

**Comment by Cissi-B** [comment]
Hi,

Thank you for the fast answer! 

I think I found the problem. I had set FastaFile=${genome}.fa.gz which did not work. However, when I unzipped the file and instead used FastaFile=${genome}.fa I did not get the error and I did get a .gem file.

**Comment by Cissi-B** [comment]
Hi again,

Unfortunately, I am getting more errors when converting the mappability file to bedgraph. I am running:

`gem-2-bed mappability -I ${genome}_index.gem -i ${genome}_${kmer}.mappability -o ${genome}_${kmer}
`
`Fatal error: exception Failure("Unrecognized commandline option 'mappability'")
`
`Fatal error: exception Failure("Unrecognized commandline option '-I'")
`
According to the documentation of gem-2-bed:

```
Usage:
 gem-2-bed

  -i|--input <file>                (default=stdin)

  -o|--output <file>               (default=stdout)

  -c|--compact                     (emit only the first six BED fields,
                                    default=false)

  --rgb-forward-scheme <8-bit_int>,<8-bit_int>,<8-bit_int>
                                   (RGB scheme for forward blocks,
                                    default=0,0,255)

  --rgb-reverse-scheme <8-bit_int>,<8-bit_int>,<8-bit_int>
                                   (RGB scheme for reverse blocks,
                                    default=255,0,0)

  --max-buffer-size <number>       (default=1000000000)

  -T|--threads <number>            (default=1)

  --show-license                   (show license and exit)

  -h|--help                        (print usage and exit)
```

I am wondering if I can skip the mappability and the -I ${genome}_index.gem and still get the correct output file?

Thank you in advance.

**Comment by lldelisle** [comment]
Which version of gem do you have? How did you installed it?

**Comment by lldelisle** [comment]
It seems that you don't have the same version as the one which is on conda:
```
(lastVersion) [ldelisle@SV-49-002 XXXX]$ gem-2-bed --help
Welcome to GEM-2-bed build 1.899 (beta) - (2019-12-26 00:28:27 GMT)
 (c) 2008-2013 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2013 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2013 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************
Usage:
 gem-2-bed
  segments ...
       (output alignments in BED format)
  blocks-coverage ...
       (accumulate blocks of consecutive matches to a BedGraph coverage track)
  splices-coverage ...
       (accumulate bases spanned by introns to a BedGraph coverage track)
  mappability ...
       (convert a GEM mappability file to a BedGraph track)
  --show-license                  (show license and exit)
  -h|--help                       (print usage and exit)

```

**Comment by Cissi-B** [comment]
Hi,

Yes, the version was wrong. I had installed gem2 with conda but there was apparently another version already installed that was used.

Thank you so much for the help!
